name: camera_android
description: Android implementation of the camera plugin.
version: 0.10.4

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camera
        pluginClass: CameraPlugin
        dartPluginClass: AndroidCamera

dependencies:
  camera_platform_interface: 2.3.2
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: 2.0.6
  stream_transform: 2.0.0

dev_dependencies:
  async: 2.9.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
